build:
    environment:
        php: '7.1.12'

    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
filter:
    excluded_paths:
        - 'tests/*'
    dependency_paths:
        - wordpress/

checks:
    php:
        code_rating: true
        duplication: true
