checks:
    php:
        psr2_switch_declaration: false
        psr2_class_declaration: false
        side_effects_or_types: false
        no_global_keyword: false
        no_exit: false
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true

filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    nodes:
        analysis:
            project_setup:
                override: ['true']
            tests:
                override: [php-scrutinizer-run]

tools:
  php_mess_detector:
    config:
      code_size_rules:
        cyclomatic_complexity: true
        npath_complexity: true
        excessive_method_length: true
        excessive_class_length: true
        excessive_parameter_list: true
        excessive_public_count: true
        too_many_fields: true
        too_many_methods: true
        excessive_class_complexity: true
      design_rules:
        number_of_class_children: true
        depth_of_inheritance: true
        coupling_between_objects: true
      unused_code_rules:
        unused_local_variable: true
        unused_private_method: true
        unused_formal_parameter: true
      naming_rules:
        long_variable: true
        short_method: true
        boolean_method_name: true
  php_cs_fixer:
    config:
      level: all
      fixers:
        unused_use: true
        phpdoc_params: true
        braces: false
        php_closing_tag: true
  php_analyzer:
    config:
      suspicious_code:
        enabled: true
        overriding_parameter: true
        overriding_closure_use: true
        parameter_closure_use_conflict: true
        parameter_multiple_times: true
        non_existent_class_in_instanceof_check: true
        non_existent_class_in_catch_clause: true
        assignment_of_null_return: true
        non_commented_switch_fallthrough: true
        non_commented_empty_catch_block: true
        overriding_private_members: true
        use_statement_alias_conflict: true
        precedence_in_condition_assignment: true
      verify_php_doc_comments:
        enabled: true
        parameters: true
        return: true
        suggest_more_specific_types: true
        ask_for_return_if_not_inferrable: true
        ask_for_param_type_annotation: true
      loops_must_use_braces:
        enabled: true
      simplify_boolean_return:
        enabled: true
      phpunit_checks:
        enabled: true
      reflection_fixes:
        enabled: true
      parameter_reference_check:
        enabled: true
      unreachable_code:
        enabled: true
      check_access_control:
        enabled: true
      typo_checks:
        enabled: true
      check_variables:
        enabled: true
      check_calls:
        enabled: true
        too_many_arguments: true
        missing_argument: true
        argument_type_checks: lenient
      dead_assignments:
        enabled: true
      check_usage_context:
        enabled: true
        foreach:
          value_as_reference: true
          traversable: true
      reflection_checks:
        enabled: false
      precedence_checks:
        enabled: true
        assignment_in_condition: true
        comparison_of_bit_result: true
      basic_semantic_checks:
        enabled: true
      unused_code:
        enabled: true
      deprecation_checks:
        enabled: true
      useless_function_calls:
        enabled: true
      metrics_lack_of_cohesion_methods:
        enabled: true
      metrics_coupling:
        enabled: true
      doctrine_parameter_binding:
        enabled: false
      doctrine_entity_manager_injection:
        enabled: false
      symfony_request_injection:
        enabled: false
      doc_comment_fixes:
        enabled: false
  php_code_sniffer:
    config:
      standard: WordPress
      sniffs:
        wordpress:
          arrays:
            array_declaration_sniff: true
          files:
            file_name_sniff: false
          formatting:
            multiple_statement_alignment_sniff: false
          functions:
            function_call_signature_sniff: false
            function_declaration_argument_spacing_sniff: false
          naming_conventions:
            valid_function_name_sniff: false
          objects:
            object_instantiation_sniff: true
          php:
            discouraged_functions_sniff: true
          strings:
            double_quote_usage_sniff: true
          white_space:
            control_structure_spacing_sniff: false
            operator_spacing_sniff: false
            php_indent_sniff: false
          xss:
            escape_output_sniff: true
        squiz:
          control_structures:
            for_loop_declaration_sniff: false
            for_each_loop_declaration_sniff: false
  sensiolabs_security_checker: true
  php_loc: true
  php_pdepend: true
  php_sim: true
  php_changetracking: true
